# Generated by Django 2.2.5 on 2019-10-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=200)),
                ('desc', models.TextField()),
                ('preco', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.Vendedor')),
            ],
        ),
    ]
