# Generated by Django 2.2.5 on 2019-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_imagem_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texto',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='caminho',
            field=models.CharField(max_length=50),
        ),
    ]
