# Generated by Django 2.2.5 on 2019-10-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_auto_20191014_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='nome',
        ),
    ]
